config/routes.rb
Rails.application.routes.draw do
  resources :stocks
  devise_for :users
  get 'home/index'
  get 'home/about'
  post 'home/index'
  root "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stock.rb
class Stock < ApplicationRecord
     belongs_to:user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many:stocks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if params[:id] == ""
      @nothing = "Hey do you forget to enter any name??"
    elsif 
      if params[:id]
        begin
         @stock = StockQuote::Stock.quote(params[:id])
        rescue 
         @error = "Hey thats not a stock..search in google!!"
        end
      end
    end

    def about
    end
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit,:update,:destroy]
  before_action :authenticate_user!

  # GET /stocks
  # GET /stocks.json
  def index
    @stocks = Stock.all
  end

  # GET /stocks/1
  # GET /stocks/1.json
  def show
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks
  # POST /stocks.json
  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to @stock, notice: 'Stock was successfully created.' }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1
  # PATCH/PUT /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to @stock, notice: 'Stock was successfully updated.' }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1
  # DELETE /stocks/1.json
  def destroy
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to stocks_url, notice: 'Stock was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stock_params
      params.require(:stock).permit(:ticker, :user_id)
    end
    
    def correct_user
      @ticker=current_user.stocks.find_by(id:params[:id])
      redirect_to stocks_path,notice:"Not authoritative" if @ticker.nil?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/home/_navbar.html.erb
     <%= link_to "Home",home_index_path %>|
     <%= link_to "About us",home_about_path %>|
     <% if user_signed_in? %>
       <%= link_to "Log out",destroy_user_session_path, method: :delete %>|
       <%= link_to "Update your profile",edit_user_registration_path %>|
       <%= link_to "Create new stock",new_stock_path %>|
       <%= link_to "List your stocks",stocks_path %>
     <% else %>
       <%= link_to "Log in",new_user_session_path %>|
       <%= link_to "Sign up",new_user_registration_path %>
     <% end %>
    
    

app/views/home/about.html.erb
<h1>About us!</h1>
<p>This is my first site</p>

app/views/home/index.html.erb
<%= form_tag home_index_path, :method=>"post" do %>
  <%= text_field_tag 'id', nil, placeholder:'Enter Company name',size:50 %>
  <%= submit_tag 'Submit' %>
<% end %>

<br/>


<% if @stock %>
<%= @stock.inspect %>
<% elsif @nothing %>
<%= @nothing %>
<% end %>

<% if @error %>
<%= @error %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Testapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

     <%= render 'home/navbar' %>
     <p class="notice"><%= notice %></p>
     <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/stocks/_form.html.erb
<%= form_with(model: stock, local: true) do |form| %>
  <% if stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
      <% stock.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ticker %>
    <%= form.text_field :ticker %>
  </div>

  <div class="field">
    
    <%= form.text_field :user_id,value: current_user.id, type: :hidden %>
  </div>
  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stocks/edit.html.erb
<h1>Editing Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stocks</h1>

<table>
  <thead>
    <tr>
      <th>Ticker</th>|
      <th>Current Price</th>|
      <th>Market Capital</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stocks.each do |stock| %>
    <% if stock.user_id == current_user.id %>
        <% begin %>
         <% @stock_quote = StockQuote::Stock.quote(stock.ticker) %>
        <% rescue StandardError %>
        <tr>
         <td><%= stock.ticker %></td>
         <td><%= "NA" %></td>
         <td><%= "NA" %></td>
         <td><%= link_to 'Show', stock %></td>
         <td><%= link_to 'Edit', edit_stock_path(stock) %></td>
        <td><%= link_to 'Destroy', stock, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% next %>
        <% end %>
      <tr>
        <td><%= stock.ticker %></td>
        <td><%= @stock_quote.latest_price %></td>
        <td><%= @stock_quote.avg_total_volume %></td>
        <td><%= link_to 'Show', stock %></td>
        <td><%= link_to 'Edit', edit_stock_path(stock) %></td>
        <td><%= link_to 'Destroy', stock, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %> 
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stock', new_stock_path %>

app/views/stocks/new.html.erb
<h1>New Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Back', stocks_path %>

app/views/stocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ticker:</strong>
  <%= @stock.ticker %>
</p>

<p>
  <strong>User:</strong>
  <%= @stock.user_id %>
</p>

<%= link_to 'Edit', edit_stock_path(@stock) %> |
<%= link_to 'Back', stocks_path %>